# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EventDating' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EventDating

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  
  target 'EventDating-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EventDatingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'EventDating-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EventDating-tvOS

  #target 'EventDating-tvOSTests' do
 #   inherit! :search_paths
    # Pods for testing
#  end

#end
